"""frappe_armenia.coa — Armenian Chart of Accounts (COA) fixture.

This module is the authoritative source of the Armenian-standard chart of
accounts used by the `frappe_armenia` app. The taxonomy follows Chapter 9
of the Armenian Tax Code (ՀՀ հարկային օրենսգիրք, Գլուխ 9) and the chart-of-accounts
structure commonly used by Armenian SMEs and accounting software.

Public API:
    build_coa_tree() -> list[dict]
        Return the in-memory COA as a list of dicts with these keys:
            account_number, account_name_en, account_name_hy, root_type,
            account_type, parent_account_number, is_group, account_currency

    count_by_root_type(tree) -> dict[str, int]
        Return a tally of accounts by root_type.

    seed_armenian_coa(company: str) -> int
        Insert every account in the tree into the live Account DocType for
        the given company. Idempotent: skips any account_number that
        already exists for the company. Returns the number of accounts
        actually inserted (excludes pre-existing).

The tree contains ~350 accounts. Numbers are aligned with the chapter
ranges in the task spec:
    1xxx  non-current assets     (Asset)
    2xxx  current assets         (Asset)
    3xxx  equity                 (Equity)
    4xxx  non-current liabs.     (Liability)
    5xxx  current liabilities    (Liability)
    6xxx  income                 (Income)
    7xxx  expenses               (Expense)
    8xxx  off-balance-sheet      (Asset/Liability depending on sub-type)
    9xxx  cost of goods sold     (Expense)

Note: 8xxx is informational and mapped to Liability by default in
`root_type` (off-balance-sheet items like guarantees and commitments
are typically tracked under liabilities in Armenian accounting practice).
"""
from collections import Counter


# ---------------------------------------------------------------------------
# COA data
# ---------------------------------------------------------------------------
# Each entry is a dict with the same keys as build_coa_tree() returns.
# The list is ordered so parents always come before their children
# (the seeder relies on this two-pass property).

COA_ENTRIES = [
    # =================== 1. NON-CURRENT ASSETS (1000-1999) ===================
    {"account_number": "1000", "account_name_en": "Non-current Assets",
     "account_name_hy": "Հիմնական միջոցներ",
     "root_type": "Asset", "account_type": None, "parent_account_number": None,
     "is_group": 1},
    # --- 1.1 Intangible Assets (1100-1199) ---
    {"account_number": "1100", "account_name_en": "Intangible Assets",
     "account_name_hy": "Աննյութական ակտիվներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1000",
     "is_group": 1},
    {"account_number": "1110", "account_name_en": "Software",
     "account_name_hy": "Ծրագրային ապահովում",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1100",
     "is_group": 0},
    {"account_number": "1111", "account_name_en": "Acquired Software",
     "account_name_hy": "Ձեռքբերված ծրագրային ապահովում",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1110",
     "is_group": 0},
    {"account_number": "1112", "account_name_en": "Internally Developed Software",
     "account_name_hy": "Ներքին մշակված ծրագրային ապահովում",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1110",
     "is_group": 0},
    {"account_number": "1113", "account_name_en": "Software under Development",
     "account_name_hy": "Մշակման փուլում գտնվող ծրագրեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1110",
     "is_group": 0},
    {"account_number": "1120", "account_name_en": "Licenses",
     "account_name_hy": "Լիցենզիաներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1100",
     "is_group": 1},
    {"account_number": "1121", "account_name_en": "Software Licenses",
     "account_name_hy": "Ծրագրային լիցենզիաներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1120",
     "is_group": 0},
    {"account_number": "1122", "account_name_en": "Patent Licenses",
     "account_name_hy": "Արտոնագրային լիցենզիաներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1120",
     "is_group": 0},
    {"account_number": "1123", "account_name_en": "Trademark Licenses",
     "account_name_hy": "Ապրանքանիշի լիցենզիաներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1120",
     "is_group": 0},
    {"account_number": "1130", "account_name_en": "Patents",
     "account_name_hy": "Արտոնագրեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1100",
     "is_group": 0},
    {"account_number": "1131", "account_name_en": "Industrial Designs",
     "account_name_hy": "Արդյունաբերական նմուշներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1100",
     "is_group": 0},
    {"account_number": "1132", "account_name_en": "Trademarks",
     "account_name_hy": "Ապրանքանիշեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1100",
     "is_group": 0},
    {"account_number": "1140", "account_name_en": "Goodwill",
     "account_name_hy": "Գուդվիլ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1100",
     "is_group": 0},
    {"account_number": "1150", "account_name_en": "Research and Development",
     "account_name_hy": "Հետազոտություններ և մշակումներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1100",
     "is_group": 0},
    {"account_number": "1190", "account_name_en": "Accumulated Amortization - Intangibles",
     "account_name_hy": "Կուտակված արժեկում՝ աննյութական ակտիվներ",
     "root_type": "Asset", "account_type": "Accumulated Depreciation",
     "parent_account_number": "1100", "is_group": 1},
    {"account_number": "1191", "account_name_en": "Accumulated Amortization - Software",
     "account_name_hy": "Կուտակված արժեկում՝ ծրագրեր",
     "root_type": "Asset", "account_type": "Accumulated Depreciation",
     "parent_account_number": "1190", "is_group": 0},
    {"account_number": "1192", "account_name_en": "Accumulated Amortization - Licenses",
     "account_name_hy": "Կուտակված արժեկում՝ լիցենզիաներ",
     "root_type": "Asset", "account_type": "Accumulated Depreciation",
     "parent_account_number": "1190", "is_group": 0},
    {"account_number": "1193", "account_name_en": "Accumulated Amortization - Patents",
     "account_name_hy": "Կուտակված արժեկում՝ արտոնագրեր",
     "root_type": "Asset", "account_type": "Accumulated Depreciation",
     "parent_account_number": "1190", "is_group": 0},
    # --- 1.2 Tangible Assets (1200-1299) ---
    {"account_number": "1200", "account_name_en": "Tangible Fixed Assets",
     "account_name_hy": "Նյութական հիմնական միջոցներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1000",
     "is_group": 1},
    {"account_number": "1210", "account_name_en": "Land",
     "account_name_hy": "Հողատարածք",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1200",
     "is_group": 1},
    {"account_number": "1211", "account_name_en": "Land - Operational Use",
     "account_name_hy": "Հողատարածք՝ գործառնական օգտագործման",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1210",
     "is_group": 0},
    {"account_number": "1212", "account_name_en": "Land - Investment Property",
     "account_name_hy": "Հողատարածք՝ ներդրումային գույք",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1210",
     "is_group": 0},
    {"account_number": "1220", "account_name_en": "Buildings",
     "account_name_hy": "Շենքեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1200",
     "is_group": 1},
    {"account_number": "1221", "account_name_en": "Office Buildings",
     "account_name_hy": "Գրասենյակային շենքեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1220",
     "is_group": 0},
    {"account_number": "1222", "account_name_en": "Production Buildings",
     "account_name_hy": "Արտադրական շենքեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1220",
     "is_group": 0},
    {"account_number": "1223", "account_name_en": "Warehouse Buildings",
     "account_name_hy": "Պահեստային շենքեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1220",
     "is_group": 0},
    {"account_number": "1224", "account_name_en": "Buildings under Construction",
     "account_name_hy": "Կառուցման փուլում գտնվող շենքեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1220",
     "is_group": 0},
    {"account_number": "1230", "account_name_en": "Machinery and Equipment",
     "account_name_hy": "Մեքենաներ և սարքավորանքներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1200",
     "is_group": 1},
    {"account_number": "1231", "account_name_en": "Production Machinery",
     "account_name_hy": "Արտադրական մեքենաներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1230",
     "is_group": 0},
    {"account_number": "1232", "account_name_en": "Office Equipment",
     "account_name_hy": "Գրասենյակային սարքավորանք",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1230",
     "is_group": 0},
    {"account_number": "1233", "account_name_en": "Computer Equipment",
     "account_name_hy": "Համակարգչային սարքավորանք",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1230",
     "is_group": 0},
    {"account_number": "1234", "account_name_en": "Laboratory Equipment",
     "account_name_hy": "Լաբորատոր սարքավորանք",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1230",
     "is_group": 0},
    {"account_number": "1240", "account_name_en": "Vehicles",
     "account_name_hy": "Տրանսպորտային միջոցներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1200",
     "is_group": 1},
    {"account_number": "1241", "account_name_en": "Passenger Vehicles",
     "account_name_hy": "Ուղևորատար մեքենաներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1240",
     "is_group": 0},
    {"account_number": "1242", "account_name_en": "Cargo Vehicles",
     "account_name_hy": "Բեռնատար մեքենաներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1240",
     "is_group": 0},
    {"account_number": "1243", "account_name_en": "Special Purpose Vehicles",
     "account_name_hy": "Հատուկ նշանակության մեքենաներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1240",
     "is_group": 0},
    {"account_number": "1250", "account_name_en": "Furniture and Fixtures",
     "account_name_hy": "Կահույք և պարագաներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1200",
     "is_group": 0},
    {"account_number": "1251", "account_name_en": "Office Furniture",
     "account_name_hy": "Գրասենյակային կահույք",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1250",
     "is_group": 0},
    {"account_number": "1252", "account_name_en": "Shop Fixtures",
     "account_name_hy": "Խանութի պարագաներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1250",
     "is_group": 0},
    {"account_number": "1260", "account_name_en": "Leasehold Improvements",
     "account_name_hy": "Վարձակալական բարելավումներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1200",
     "is_group": 0},
    {"account_number": "1270", "account_name_en": "Biological Assets",
     "account_name_hy": "Կենսաբանական ակտիվներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1200",
     "is_group": 1},
    {"account_number": "1271", "account_name_en": "Livestock",
     "account_name_hy": "Անասուններ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1270",
     "is_group": 0},
    {"account_number": "1272", "account_name_en": "Plantations",
     "account_name_hy": "Տնկարկներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1270",
     "is_group": 0},
    {"account_number": "1290", "account_name_en": "Accumulated Depreciation - Tangibles",
     "account_name_hy": "Կուտակված մաշվածք՝ նյութական հիմնական միջոցներ",
     "root_type": "Asset", "account_type": "Accumulated Depreciation",
     "parent_account_number": "1200", "is_group": 1},
    {"account_number": "1291", "account_name_en": "Accumulated Depreciation - Buildings",
     "account_name_hy": "Կուտակված մաշվածք՝ շենքեր",
     "root_type": "Asset", "account_type": "Accumulated Depreciation",
     "parent_account_number": "1290", "is_group": 0},
    {"account_number": "1292", "account_name_en": "Accumulated Depreciation - Machinery",
     "account_name_hy": "Կուտակված մաշվածք՝ մեքենաներ",
     "root_type": "Asset", "account_type": "Accumulated Depreciation",
     "parent_account_number": "1290", "is_group": 0},
    {"account_number": "1293", "account_name_en": "Accumulated Depreciation - Vehicles",
     "account_name_hy": "Կուտակված մաշվածք՝ մեքենաներ",
     "root_type": "Asset", "account_type": "Accumulated Depreciation",
     "parent_account_number": "1290", "is_group": 0},
    {"account_number": "1294", "account_name_en": "Accumulated Depreciation - Furniture",
     "account_name_hy": "Կուտակված մաշվածք՝ կահույք",
     "root_type": "Asset", "account_type": "Accumulated Depreciation",
     "parent_account_number": "1290", "is_group": 0},
    {"account_number": "1295", "account_name_en": "Accumulated Depreciation - Equipment",
     "account_name_hy": "Կուտակված մաշվածք՝ սարքավորանքներ",
     "root_type": "Asset", "account_type": "Accumulated Depreciation",
     "parent_account_number": "1290", "is_group": 0},
    # --- 1.3 Long-term financial investments (1300-1399) ---
    {"account_number": "1300", "account_name_en": "Long-term Financial Investments",
     "account_name_hy": "Երկարաժամկետ ֆինանսական ներդրումներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1000",
     "is_group": 1},
    {"account_number": "1310", "account_name_en": "Investments in Subsidiaries",
     "account_name_hy": "Ներդրումներ դուստր ձեռնարկություններում",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1300",
     "is_group": 0},
    {"account_number": "1311", "account_name_en": "Investments in Associates",
     "account_name_hy": "Ներդրումներ կապակցված ձեռնարկություններում",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1300",
     "is_group": 0},
    {"account_number": "1312", "account_name_en": "Investments in Joint Ventures",
     "account_name_hy": "Ներդրումներ համատեղ ձեռնարկություններում",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1300",
     "is_group": 0},
    {"account_number": "1320", "account_name_en": "Long-term Loans Granted",
     "account_name_hy": "Տրամադրված երկարաժամկետ վարկեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1300",
     "is_group": 1},
    {"account_number": "1321", "account_name_en": "Loans to Employees",
     "account_name_hy": "Վարկեր աշխատակիցներին",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1320",
     "is_group": 0},
    {"account_number": "1322", "account_name_en": "Loans to Related Parties",
     "account_name_hy": "Վարկեր կապակցված կողմերին",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1320",
     "is_group": 0},
    {"account_number": "1323", "account_name_en": "Loans to Other Entities",
     "account_name_hy": "Վարկեր այլ ձեռնարկություններին",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1320",
     "is_group": 0},
    {"account_number": "1330", "account_name_en": "Long-term Securities Held",
     "account_name_hy": "Պահվող երկարաժամկետ արժեթղթեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1300",
     "is_group": 1},
    {"account_number": "1331", "account_name_en": "Government Bonds",
     "account_name_hy": "Պետական պարտատոմսեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1330",
     "is_group": 0},
    {"account_number": "1332", "account_name_en": "Corporate Bonds",
     "account_name_hy": "Կորպորատիվ պարտատոմսեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1330",
     "is_group": 0},
    {"account_number": "1340", "account_name_en": "Long-term Receivables",
     "account_name_hy": "Երկարաժամկետ պարտքային պահանջներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1300",
     "is_group": 0},
    {"account_number": "1350", "account_name_en": "Investment Property",
     "account_name_hy": "Ներդրումային գույք",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1300",
     "is_group": 0},
    # --- 1.4 Deferred tax (1400-1499) ---
    {"account_number": "1400", "account_name_en": "Deferred Tax Assets",
     "account_name_hy": "Հետաձգված հարկային ակտիվներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1000",
     "is_group": 1},
    {"account_number": "1410", "account_name_en": "Deferred Tax - Fixed Assets",
     "account_name_hy": "Հետաձգված հարկ՝ հիմնական միջոցներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1400",
     "is_group": 0},
    {"account_number": "1411", "account_name_en": "Deferred Tax - Provisions",
     "account_name_hy": "Հետաձգված հարկ՝ պահուստներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1400",
     "is_group": 0},
    {"account_number": "1412", "account_name_en": "Deferred Tax - Tax Loss Carryforward",
     "account_name_hy": "Հետաձգված հարկ՝ վնասի փոխանցում",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1400",
     "is_group": 0},
    {"account_number": "1420", "account_name_en": "Other Non-current Assets",
     "account_name_hy": "Այլ հիմնական միջոցներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1000",
     "is_group": 1},
    {"account_number": "1421", "account_name_en": "Prepaid Long-term Expenses",
     "account_name_hy": "Նախավճարային երկարաժամկետ ծախսեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1420",
     "is_group": 0},
    {"account_number": "1422", "account_name_en": "Long-term Prepayments",
     "account_name_hy": "Երկարաժամկետ կանխավճարներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1420",
     "is_group": 0},
    {"account_number": "1430", "account_name_en": "Intangible Assets in Progress",
     "account_name_hy": "Աննյութական ակտիվներ ընթացքում",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1000",
     "is_group": 0},
    {"account_number": "1440", "account_name_en": "Capital Work in Progress",
     "account_name_hy": "Կապիտալ շինարարություն ընթացքում",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "1000",
     "is_group": 0},

    # =================== 2. CURRENT ASSETS (2000-2999) ===================
    {"account_number": "2000", "account_name_en": "Current Assets",
     "account_name_hy": "Շրջանառվող միջոցներ",
     "root_type": "Asset", "account_type": None, "parent_account_number": None,
     "is_group": 1},
    # --- 2.1 Inventories (2100-2199) ---
    {"account_number": "2100", "account_name_en": "Inventories",
     "account_name_hy": "Պաշարներ",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2000",
     "is_group": 1},
    {"account_number": "2110", "account_name_en": "Raw Materials",
     "account_name_hy": "Հումք և նյութեր",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2100",
     "is_group": 1},
    {"account_number": "2111", "account_name_en": "Basic Raw Materials",
     "account_name_hy": "Հիմնական հումք",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2110",
     "is_group": 0},
    {"account_number": "2112", "account_name_en": "Auxiliary Materials",
     "account_name_hy": "Օժանդակ նյութեր",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2110",
     "is_group": 0},
    {"account_number": "2113", "account_name_en": "Spare Parts",
     "account_name_hy": "Պահեստամասեր",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2110",
     "is_group": 0},
    {"account_number": "2114", "account_name_en": "Fuel and Lubricants",
     "account_name_hy": "Վառելիք և քսայուղեր",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2110",
     "is_group": 0},
    {"account_number": "2120", "account_name_en": "Work in Progress",
     "account_name_hy": "Անավարտ արտադրություն",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2100",
     "is_group": 0},
    {"account_number": "2130", "account_name_en": "Finished Goods",
     "account_name_hy": "Պատրաստի արտադրանք",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2100",
     "is_group": 0},
    {"account_number": "2140", "account_name_en": "Merchandise (Goods for Resale)",
     "account_name_hy": "Ապրանքներ (վերավաճառքի համար)",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2100",
     "is_group": 0},
    {"account_number": "2150", "account_name_en": "Packaging Materials",
     "account_name_hy": "Փաթեթավորման նյութեր",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2100",
     "is_group": 0},
    {"account_number": "2160", "account_name_en": "Inventory in Transit",
     "account_name_hy": "Ճանապարհին գտնվող պաշարներ",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2100",
     "is_group": 0},
    {"account_number": "2170", "account_name_en": "Inventory at Third Parties",
     "account_name_hy": "Երրորդ անձանց մոտ գտնվող պաշարներ",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2100",
     "is_group": 0},
    {"account_number": "2180", "account_name_en": "Low-Value and Wear Items",
     "account_name_hy": "Ցածրարժեք և արագ մաշվող առարկաներ",
     "root_type": "Asset", "account_type": "Stock", "parent_account_number": "2100",
     "is_group": 0},
    {"account_number": "2190", "account_name_en": "Inventory Provisions",
     "account_name_hy": "Պաշարների արժեզրկման պահուստ",
     "root_type": "Asset", "account_type": "Stock Adjustment",
     "parent_account_number": "2100", "is_group": 0},
    # --- 2.2 Trade Receivables (2200-2299) ---
    {"account_number": "2200", "account_name_en": "Trade Receivables",
     "account_name_hy": "Առևտրային պարտքատերեր",
     "root_type": "Asset", "account_type": "Receivable", "parent_account_number": "2000",
     "is_group": 1},
    {"account_number": "2210", "account_name_en": "Accounts Receivable - Trade",
     "account_name_hy": "Հաշիվների պարտք՝ առևտրային",
     "root_type": "Asset", "account_type": "Receivable",
     "parent_account_number": "2200", "is_group": 0},
    {"account_number": "2211", "account_name_en": "Local Customers",
     "account_name_hy": "Տեղական հաճախորդներ",
     "root_type": "Asset", "account_type": "Receivable",
     "parent_account_number": "2210", "is_group": 0},
    {"account_number": "2212", "account_name_en": "Foreign Customers",
     "account_name_hy": "Օտարերկրյա հաճախորդներ",
     "root_type": "Asset", "account_type": "Receivable",
     "parent_account_number": "2210", "is_group": 0},
    {"account_number": "2213", "account_name_en": "Government Customers",
     "account_name_hy": "Պետական հաճախորդներ",
     "root_type": "Asset", "account_type": "Receivable",
     "parent_account_number": "2210", "is_group": 0},
    {"account_number": "2220", "account_name_en": "Notes Receivable",
     "account_name_hy": "Ստացվող վեկսելներ",
     "root_type": "Asset", "account_type": "Receivable",
     "parent_account_number": "2200", "is_group": 0},
    {"account_number": "2230", "account_name_en": "Allowance for Doubtful Debts",
     "account_name_hy": "Կասկածելի պարտքերի պահուստ",
     "root_type": "Asset", "account_type": "Receivable",
     "parent_account_number": "2200", "is_group": 0},
    # --- 2.3 Cash and equivalents (2300-2399) ---
    {"account_number": "2300", "account_name_en": "Cash and Cash Equivalents",
     "account_name_hy": "Կանխիկ և դրանց համարժերներ",
     "root_type": "Asset", "account_type": "Cash", "parent_account_number": "2000",
     "is_group": 1},
    {"account_number": "2310", "account_name_en": "Cash on Hand - AMD",
     "account_name_hy": "Ձեռքի կանխիկ՝ ՀՀ դրամ",
     "root_type": "Asset", "account_type": "Cash", "parent_account_number": "2300",
     "is_group": 0},
    {"account_number": "2311", "account_name_en": "Cash on Hand - Office",
     "account_name_hy": "Ձեռքի կանխիկ՝ գրասենյակ",
     "root_type": "Asset", "account_type": "Cash", "parent_account_number": "2310",
     "is_group": 0},
    {"account_number": "2312", "account_name_en": "Cash on Hand - Cashier",
     "account_name_hy": "Ձեռքի կանխիկ՝ դրամարկղ",
     "root_type": "Asset", "account_type": "Cash", "parent_account_number": "2310",
     "is_group": 0},
    {"account_number": "2320", "account_name_en": "Cash on Hand - Foreign Currency",
     "account_name_hy": "Ձեռքի կանխիկ՝ արտարժույթ",
     "root_type": "Asset", "account_type": "Cash", "parent_account_number": "2300",
     "is_group": 0},
    {"account_number": "2321", "account_name_en": "Cash on Hand - USD",
     "account_name_hy": "Ձեռքի կանխիկ՝ ԱՄՆ դոլար",
     "root_type": "Asset", "account_type": "Cash", "parent_account_number": "2320",
     "is_group": 0},
    {"account_number": "2322", "account_name_en": "Cash on Hand - EUR",
     "account_name_hy": "Ձեռքի կանխիկ՝ Եվրո",
     "root_type": "Asset", "account_type": "Cash", "parent_account_number": "2320",
     "is_group": 0},
    {"account_number": "2323", "account_name_en": "Cash on Hand - RUB",
     "account_name_hy": "Ձեռքի կանխիկ՝ Ռուսական ռուբլի",
     "root_type": "Asset", "account_type": "Cash", "parent_account_number": "2320",
     "is_group": 0},
    {"account_number": "2330", "account_name_en": "Bank Accounts - AMD",
     "account_name_hy": "Բանկային հաշիվներ՝ ՀՀ դրամ",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2300",
     "is_group": 0},
    {"account_number": "2331", "account_name_en": "Bank Account - Ameriabank AMD",
     "account_name_hy": "Բանկային հաշիվ՝ Ամերիաբանկ ՀՀ դրամ",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2330",
     "is_group": 0},
    {"account_number": "2332", "account_name_en": "Bank Account - Ardshinbank AMD",
     "account_name_hy": "Բանկային հաշիվ՝ Արդշինբանկ ՀՀ դրամ",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2330",
     "is_group": 0},
    {"account_number": "2333", "account_name_en": "Bank Account - HSBC Armenia AMD",
     "account_name_hy": "Բանկային հաշիվ՝ HSBC Հայաստան ՀՀ դրամ",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2330",
     "is_group": 0},
    {"account_number": "2334", "account_name_en": "Bank Account - Converse Bank AMD",
     "account_name_hy": "Բանկային հաշիվ՝ Կոնվերս Բանկ ՀՀ դրամ",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2330",
     "is_group": 0},
    {"account_number": "2335", "account_name_en": "Bank Account - Central Bank of Armenia",
     "account_name_hy": "Բանկային հաշիվ՝ ՀՀ Կենտրոնական բանկ",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2330",
     "is_group": 0},
    {"account_number": "2340", "account_name_en": "Bank Accounts - Foreign Currency",
     "account_name_hy": "Բանկային հաշիվներ՝ արտարժույթ",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2300",
     "is_group": 0},
    {"account_number": "2341", "account_name_en": "Bank Account - USD",
     "account_name_hy": "Բանկային հաշիվ՝ ԱՄՆ դոլար",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2340",
     "is_group": 0},
    {"account_number": "2342", "account_name_en": "Bank Account - EUR",
     "account_name_hy": "Բանկային հաշիվ՝ Եվրո",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2340",
     "is_group": 0},
    {"account_number": "2343", "account_name_en": "Bank Account - RUB",
     "account_name_hy": "Բանկային հաշիվ՝ Ռուսական ռուբլի",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2340",
     "is_group": 0},
    {"account_number": "2350", "account_name_en": "Bank Cards Receivable",
     "account_name_hy": "Բանկային քարտերի պարտքեր",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2300",
     "is_group": 0},
    {"account_number": "2360", "account_name_en": "Short-term Deposits",
     "account_name_hy": "Կարճաժամկետ ավանդներ",
     "root_type": "Asset", "account_type": "Bank", "parent_account_number": "2300",
     "is_group": 0},
    {"account_number": "2370", "account_name_en": "Money in Transit",
     "account_name_hy": "Ճանապարհին գտնվող դրամ",
     "root_type": "Asset", "account_type": "Cash", "parent_account_number": "2300",
     "is_group": 0},
    {"account_number": "2380", "account_name_en": "Petty Cash",
     "account_name_hy": "Մանր կանխիկ",
     "root_type": "Asset", "account_type": "Cash", "parent_account_number": "2300",
     "is_group": 0},
    # --- 2.4 Prepayments and other (2400-2499) ---
    {"account_number": "2400", "account_name_en": "Prepayments and Other Current Assets",
     "account_name_hy": "Նախավճարներ և այլ շրջանառվող ակտիվներ",
     "root_type": "Asset", "account_type": None, "parent_account_number": "2000",
     "is_group": 1},
    {"account_number": "2410", "account_name_en": "Prepaid Expenses",
     "account_name_hy": "Նախավճարային ծախսեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "2400",
     "is_group": 0},
    {"account_number": "2411", "account_name_en": "Prepaid Rent",
     "account_name_hy": "Նախավճարային վարձավճար",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "2410",
     "is_group": 0},
    {"account_number": "2412", "account_name_en": "Prepaid Insurance",
     "account_name_hy": "Նախավճարային ապահովագրություն",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "2410",
     "is_group": 0},
    {"account_number": "2413", "account_name_en": "Prepaid Subscriptions",
     "account_name_hy": "Նախավճարային բաժանորդագրություններ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "2410",
     "is_group": 0},
    {"account_number": "2420", "account_name_en": "Advances to Suppliers",
     "account_name_hy": "Մատակարարներին տրված կանխավճարներ",
     "root_type": "Asset", "account_type": "Receivable", "parent_account_number": "2400",
     "is_group": 0},
    {"account_number": "2421", "account_name_en": "Advances - Goods",
     "account_name_hy": "Կանխավճարներ՝ ապրանքների համար",
     "root_type": "Asset", "account_type": "Receivable", "parent_account_number": "2420",
     "is_group": 0},
    {"account_number": "2422", "account_name_en": "Advances - Services",
     "account_name_hy": "Կանխավճարներ՝ ծառայությունների համար",
     "root_type": "Asset", "account_type": "Receivable", "parent_account_number": "2420",
     "is_group": 0},
    {"account_number": "2430", "account_name_en": "VAT Receivable (Input VAT)",
     "account_name_hy": "Հսկողության տակ գտնվող ԱԱՀ",
     "root_type": "Asset", "account_type": "Tax", "parent_account_number": "2400",
     "is_group": 0},
    {"account_number": "2431", "account_name_en": "VAT Receivable - Domestic",
     "account_name_hy": "Հսկողության տակ գտնվող ԱԱՀ՝ ներքին",
     "root_type": "Asset", "account_type": "Tax", "parent_account_number": "2430",
     "is_group": 0},
    {"account_number": "2432", "account_name_en": "VAT Receivable - Import",
     "account_name_hy": "Հսկողության տակ գտնվող ԱԱՀ՝ ներմուծում",
     "root_type": "Asset", "account_type": "Tax", "parent_account_number": "2430",
     "is_group": 0},
    {"account_number": "2440", "account_name_en": "Other Tax Receivables",
     "account_name_hy": "Այլ հարկային պարտքեր",
     "root_type": "Asset", "account_type": "Tax", "parent_account_number": "2400",
     "is_group": 0},
    {"account_number": "2441", "account_name_en": "Income Tax Receivable",
     "account_name_hy": "Եկամտային հարկի պարտք",
     "root_type": "Asset", "account_type": "Tax", "parent_account_number": "2440",
     "is_group": 0},
    {"account_number": "2442", "account_name_en": "Customs Duties Receivable",
     "account_name_hy": "Մաքսային տուրքերի պարտք",
     "root_type": "Asset", "account_type": "Tax", "parent_account_number": "2440",
     "is_group": 0},
    {"account_number": "2450", "account_name_en": "Other Receivables",
     "account_name_hy": "Այլ պարտքատերեր",
     "root_type": "Asset", "account_type": "Receivable", "parent_account_number": "2400",
     "is_group": 0},
    {"account_number": "2451", "account_name_en": "Receivables from Employees",
     "account_name_hy": "Աշխատակիցներից պարտքեր",
     "root_type": "Asset", "account_type": "Receivable", "parent_account_number": "2450",
     "is_group": 0},
    {"account_number": "2452", "account_name_en": "Receivables from Founders",
     "account_name_hy": "Հիմնադիրներից պարտքեր",
     "root_type": "Asset", "account_type": "Receivable", "parent_account_number": "2450",
     "is_group": 0},
    {"account_number": "2453", "account_name_en": "Receivables from Related Parties",
     "account_name_hy": "Կապակցված կողմերից պարտքեր",
     "root_type": "Asset", "account_type": "Receivable", "parent_account_number": "2450",
     "is_group": 0},
    {"account_number": "2460", "account_name_en": "Short-term Investments",
     "account_name_hy": "Կարճաժամկետ ներդրումներ",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "2400",
     "is_group": 1},
    {"account_number": "2461", "account_name_en": "Short-term Loans Granted",
     "account_name_hy": "Տրամադրված կարճաժամկետ վարկեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "2460",
     "is_group": 0},
    {"account_number": "2462", "account_name_en": "Short-term Securities Held",
     "account_name_hy": "Պահվող կարճաժամկետ արժեթղթեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "2460",
     "is_group": 0},
    {"account_number": "2470", "account_name_en": "Accrued Income",
     "account_name_hy": "Հաշվեգրված եկամուտներ",
     "root_type": "Asset", "account_type": "Receivable", "parent_account_number": "2400",
     "is_group": 0},
    {"account_number": "2480", "account_name_en": "Deferred Charges",
     "account_name_hy": "Հետաձգված ծախսեր",
     "root_type": "Asset", "account_type": "Fixed Asset", "parent_account_number": "2400",
     "is_group": 0},

    # =================== 3. EQUITY (3000-3999) ===================
    {"account_number": "3000", "account_name_en": "Equity",
     "account_name_hy": "Սեփական կապիտալ",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": None,
     "is_group": 1},
    {"account_number": "3100", "account_name_en": "Charter (Share) Capital",
     "account_name_hy": "Կանոնադրական (բաժնային) կապիտալ",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3000",
     "is_group": 1},
    {"account_number": "3110", "account_name_en": "Common Stock",
     "account_name_hy": "Սովորական բաժնետոմսեր",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3100",
     "is_group": 0},
    {"account_number": "3111", "account_name_en": "Founders' Contributions",
     "account_name_hy": "Հիմնադիրների ներդրումներ",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3110",
     "is_group": 0},
    {"account_number": "3120", "account_name_en": "Preferred Stock",
     "account_name_hy": "Առավելության բաժնետոմսեր",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3100",
     "is_group": 0},
    {"account_number": "3200", "account_name_en": "Additional Paid-in Capital",
     "account_name_hy": "Հավելյալ վճարված կապիտալ",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3000",
     "is_group": 0},
    {"account_number": "3210", "account_name_en": "Share Premium",
     "account_name_hy": "Բաժնետոմսերի պրեմիում",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3200",
     "is_group": 0},
    {"account_number": "3300", "account_name_en": "Reserves",
     "account_name_hy": "Պահուստներ",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3000",
     "is_group": 1},
    {"account_number": "3310", "account_name_en": "Statutory Reserve",
     "account_name_hy": "Պարտադիր պահուստ",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3300",
     "is_group": 0},
    {"account_number": "3320", "account_name_en": "Revaluation Reserve",
     "account_name_hy": "Վերագնահատման պահուստ",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3300",
     "is_group": 0},
    {"account_number": "3330", "account_name_en": "General Reserve",
     "account_name_hy": "Ընդհանուր պահուստ",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3300",
     "is_group": 0},
    {"account_number": "3400", "account_name_en": "Retained Earnings",
     "account_name_hy": "Չբաշխված շահույթ",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3000",
     "is_group": 1},
    {"account_number": "3410", "account_name_en": "Retained Earnings - Prior Years",
     "account_name_hy": "Չբաշխված շահույթ՝ նախորդ տարիների",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3400",
     "is_group": 0},
    {"account_number": "3420", "account_name_en": "Current Year Profit (Loss)",
     "account_name_hy": "Ընթացիկ տարվա շահույթ (վնաս)",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3400",
     "is_group": 0},
    {"account_number": "3500", "account_name_en": "Treasury Stock",
     "account_name_hy": "Սեփական բաժնետոմսեր",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3000",
     "is_group": 0},
    {"account_number": "3600", "account_name_en": "Government Subsidies",
     "account_name_hy": "Պետական դոտացիաներ",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3000",
     "is_group": 0},
    {"account_number": "3700", "account_name_en": "Other Comprehensive Income",
     "account_name_hy": "Այլ համապարփակ եկամուտ",
     "root_type": "Equity", "account_type": "Equity", "parent_account_number": "3000",
     "is_group": 0},

    # =================== 4. NON-CURRENT LIABILITIES (4000-4999) ===================
    {"account_number": "4000", "account_name_en": "Non-current Liabilities",
     "account_name_hy": "Երկարաժամկետ պարտավորություններ",
     "root_type": "Liability", "account_type": None, "parent_account_number": None,
     "is_group": 1},
    {"account_number": "4100", "account_name_en": "Long-term Bank Loans",
     "account_name_hy": "Երկարաժամկետ բանկային վարկեր",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4000", "is_group": 1},
    {"account_number": "4110", "account_name_en": "Long-term Loan - AMD",
     "account_name_hy": "Երկարաժամկետ վարկ՝ ՀՀ դրամ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4100", "is_group": 0},
    {"account_number": "4111", "account_name_en": "Loan - Ameriabank",
     "account_name_hy": "Վարկ՝ Ամերիաբանկ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4110", "is_group": 0},
    {"account_number": "4112", "account_name_en": "Loan - Ardshinbank",
     "account_name_hy": "Վարկ՝ Արդշինբանկ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4110", "is_group": 0},
    {"account_number": "4113", "account_name_en": "Loan - HSBC Armenia",
     "account_name_hy": "Վարկ՝ HSBC Հայաստան",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4110", "is_group": 0},
    {"account_number": "4114", "account_name_en": "Loan - Converse Bank",
     "account_name_hy": "Վարկ՝ Կոնվերս Բանկ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4110", "is_group": 0},
    {"account_number": "4120", "account_name_en": "Long-term Loan - Foreign Currency",
     "account_name_hy": "Երկարաժամկետ վարկ՝ արտարժույթ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4100", "is_group": 0},
    {"account_number": "4121", "account_name_en": "Long-term Loan - USD",
     "account_name_hy": "Երկարաժամկետ վարկ՝ ԱՄՆ դոլար",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4120", "is_group": 0},
    {"account_number": "4122", "account_name_en": "Long-term Loan - EUR",
     "account_name_hy": "Երկարաժամկետ վարկ՝ Եվրո",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4120", "is_group": 0},
    {"account_number": "4200", "account_name_en": "Bonds Payable",
     "account_name_hy": "Վճարման ենթակա պարտատոմսեր",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4000", "is_group": 1},
    {"account_number": "4210", "account_name_en": "Corporate Bonds",
     "account_name_hy": "Կորպորատիվ պարտատոմսեր",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4200", "is_group": 0},
    {"account_number": "4220", "account_name_en": "Convertible Bonds",
     "account_name_hy": "Փոխարկելի պարտատոմսեր",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4200", "is_group": 0},
    {"account_number": "4300", "account_name_en": "Long-term Payables",
     "account_name_hy": "Երկարաժամկետ վճարման ենթակա գումարներ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4000", "is_group": 1},
    {"account_number": "4310", "account_name_en": "Long-term Payables to Suppliers",
     "account_name_hy": "Երկարաժամկետ պարտքեր մատակարարներին",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4300", "is_group": 0},
    {"account_number": "4320", "account_name_en": "Long-term Payables to Related Parties",
     "account_name_hy": "Երկարաժամկետ պարտքեր կապակցված կողմերին",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4300", "is_group": 0},
    {"account_number": "4400", "account_name_en": "Deferred Tax Liabilities",
     "account_name_hy": "Հետաձգված հարկային պարտավորություններ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4000", "is_group": 1},
    {"account_number": "4410", "account_name_en": "Deferred Tax - Fixed Assets",
     "account_name_hy": "Հետաձգված հարկ՝ հիմնական միջոցներ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4400", "is_group": 0},
    {"account_number": "4500", "account_name_en": "Long-term Provisions",
     "account_name_hy": "Երկարաժամկետ պահուստներ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4000", "is_group": 1},
    {"account_number": "4510", "account_name_en": "Pension Provision",
     "account_name_hy": "Կենսաթոշակային պահուստ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4500", "is_group": 0},
    {"account_number": "4520", "account_name_en": "Decommissioning Provision",
     "account_name_hy": "Դուրսբերման պահուստ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4500", "is_group": 0},
    {"account_number": "4530", "account_name_en": "Warranty Provision",
     "account_name_hy": "Երաշխիքային պահուստ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4500", "is_group": 0},
    {"account_number": "4600", "account_name_en": "Other Non-current Liabilities",
     "account_name_hy": "Այլ երկարաժամկետ պարտավորություններ",
     "root_type": "Liability", "account_type": "Liability",
     "parent_account_number": "4000", "is_group": 0},

    # =================== 5. CURRENT LIABILITIES (5000-5999) ===================
    {"account_number": "5000", "account_name_en": "Current Liabilities",
     "account_name_hy": "Կարճաժամկետ պարտավորություններ",
     "root_type": "Liability", "account_type": None, "parent_account_number": None,
     "is_group": 1},
    {"account_number": "5100", "account_name_en": "Trade Payables",
     "account_name_hy": "Առևտրային պարտատերեր",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5000", "is_group": 1},
    {"account_number": "5110", "account_name_en": "Accounts Payable - Trade",
     "account_name_hy": "Հաշիվների պարտք՝ առևտրային",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5100", "is_group": 0},
    {"account_number": "5111", "account_name_en": "Local Suppliers",
     "account_name_hy": "Տեղական մատակարարներ",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5110", "is_group": 0},
    {"account_number": "5112", "account_name_en": "Foreign Suppliers",
     "account_name_hy": "Օտարերկրյա մատակարարներ",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5110", "is_group": 0},
    {"account_number": "5120", "account_name_en": "Notes Payable",
     "account_name_hy": "Վճարման ենթակա վեկսելներ",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5100", "is_group": 0},
    {"account_number": "5200", "account_name_en": "Short-term Loans",
     "account_name_hy": "Կարճաժամկետ վարկեր",
     "root_type": "Liability", "account_type": "Current Liability",
     "parent_account_number": "5000", "is_group": 1},
    {"account_number": "5210", "account_name_en": "Bank Overdrafts",
     "account_name_hy": "Բանկային օվերդրաֆտներ",
     "root_type": "Liability", "account_type": "Current Liability",
     "parent_account_number": "5200", "is_group": 0},
    {"account_number": "5220", "account_name_en": "Short-term Bank Loans",
     "account_name_hy": "Կարճաժամկետ բանկային վարկեր",
     "root_type": "Liability", "account_type": "Current Liability",
     "parent_account_number": "5200", "is_group": 0},
    {"account_number": "5230", "account_name_en": "Current Portion of Long-term Loans",
     "account_name_hy": "Երկարաժամկետ վարկերի ընթացիկ մաս",
     "root_type": "Liability", "account_type": "Current Liability",
     "parent_account_number": "5200", "is_group": 0},
    {"account_number": "5300", "account_name_en": "Tax Liabilities",
     "account_name_hy": "Հարկային պարտավորություններ",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5000", "is_group": 1},
    {"account_number": "5310", "account_name_en": "VAT Payable (Output VAT)",
     "account_name_hy": "Վճարման ենթակա ԱԱՀ",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5300", "is_group": 0},
    {"account_number": "5311", "account_name_en": "VAT Payable - Domestic Sales",
     "account_name_hy": "Վճարման ենթակա ԱԱՀ՝ ներքին վաճառք",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5310", "is_group": 0},
    {"account_number": "5312", "account_name_en": "VAT Payable - Import",
     "account_name_hy": "Վճարման ենթակա ԱԱՀ՝ ներմուծում",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5310", "is_group": 0},
    {"account_number": "5320", "account_name_en": "Profit Tax Payable",
     "account_name_hy": "Շահութահարկի պարտավորություն",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5300", "is_group": 0},
    {"account_number": "5321", "account_name_en": "Profit Tax - Current Period",
     "account_name_hy": "Շահութահարկ՝ ընթացիկ ժամանակահատված",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5320", "is_group": 0},
    {"account_number": "5322", "account_name_en": "Profit Tax - Prior Periods",
     "account_name_hy": "Շահութահարկ՝ նախորդ ժամանակահատվածներ",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5320", "is_group": 0},
    {"account_number": "5330", "account_name_en": "Income Tax (PIT) Payable",
     "account_name_hy": "Եկամտային հարկի պարտավորություն",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5300", "is_group": 0},
    {"account_number": "5340", "account_name_en": "Customs Duties Payable",
     "account_name_hy": "Մաքսային տուրքերի պարտավորություն",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5300", "is_group": 0},
    {"account_number": "5350", "account_name_en": "Property Tax Payable",
     "account_name_hy": "Գույքահարկի պարտավորություն",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5300", "is_group": 0},
    {"account_number": "5360", "account_name_en": "Land Tax Payable",
     "account_name_hy": "Հողահարկի պարտավորություն",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5300", "is_group": 0},
    {"account_number": "5370", "account_name_en": "Excise Tax Payable",
     "account_name_hy": "Ակցիզային հարկի պարտավորություն",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5300", "is_group": 0},
    {"account_number": "5380", "account_name_en": "Environmental Charges Payable",
     "account_name_hy": "Բնապահպանական վճարների պարտավորություն",
     "root_type": "Liability", "account_type": "Tax",
     "parent_account_number": "5300", "is_group": 0},
    {"account_number": "5400", "account_name_en": "Payroll Liabilities",
     "account_name_hy": "Աշխատավարձային պարտավորություններ",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5000", "is_group": 1},
    {"account_number": "5410", "account_name_en": "Wages Payable",
     "account_name_hy": "Վճարման ենթակա աշխատավարձ",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5400", "is_group": 0},
    {"account_number": "5420", "account_name_en": "Accrued Salaries",
     "account_name_hy": "Հաշվեգրված աշխատավարձեր",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5400", "is_group": 0},
    {"account_number": "5430", "account_name_en": "Vacation Pay Provision",
     "account_name_hy": "Արձակուրդային վճարման պահուստ",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5400", "is_group": 0},
    {"account_number": "5500", "account_name_en": "Social Security Payable",
     "account_name_hy": "Սոցիալական ապահովության պարտավորություն",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5000", "is_group": 1},
    {"account_number": "5510", "account_name_en": "Pension Fund Payable",
     "account_name_hy": "Կենսաթոշակային ֆոնդի պարտավորություն",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5500", "is_group": 0},
    {"account_number": "5520", "account_name_en": "Social Contributions Payable",
     "account_name_hy": "Սոցիալական վճարների պարտավորություն",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5500", "is_group": 0},
    {"account_number": "5530", "account_name_en": "Medical Insurance Payable",
     "account_name_hy": "Բժշկական ապահովագրության պարտավորություն",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5500", "is_group": 0},
    {"account_number": "5600", "account_name_en": "Accrued Expenses",
     "account_name_hy": "Հաշվեգրված ծախսեր",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5000", "is_group": 1},
    {"account_number": "5610", "account_name_en": "Accrued Utilities",
     "account_name_hy": "Հաշվեգրված կոմունալ ծախսեր",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5600", "is_group": 0},
    {"account_number": "5620", "account_name_en": "Accrued Interest",
     "account_name_hy": "Հաշվեգրված տոկոսներ",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5600", "is_group": 0},
    {"account_number": "5700", "account_name_en": "Deferred Income",
     "account_name_hy": "Հետաձգված եկամուտ",
     "root_type": "Liability", "account_type": "Income Account",
     "parent_account_number": "5000", "is_group": 1},
    {"account_number": "5710", "account_name_en": "Deferred Grants",
     "account_name_hy": "Հետաձգված դոտացիաներ",
     "root_type": "Liability", "account_type": "Income Account",
     "parent_account_number": "5700", "is_group": 0},
    {"account_number": "5720", "account_name_en": "Unearned Revenue",
     "account_name_hy": "Չվաստակած եկամուտ",
     "root_type": "Liability", "account_type": "Income Account",
     "parent_account_number": "5700", "is_group": 0},
    {"account_number": "5800", "account_name_en": "Other Payables",
     "account_name_hy": "Այլ պարտատերեր",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5000", "is_group": 1},
    {"account_number": "5810", "account_name_en": "Payables to Founders",
     "account_name_hy": "Պարտքեր հիմնադիրներին",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5800", "is_group": 0},
    {"account_number": "5820", "account_name_en": "Payables to Employees",
     "account_name_hy": "Պարտքեր աշխատակիցներին",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5800", "is_group": 0},
    {"account_number": "5830", "account_name_en": "Dividends Payable",
     "account_name_hy": "Վճարման ենթակա դիվիդենդներ",
     "root_type": "Liability", "account_type": "Payable",
     "parent_account_number": "5800", "is_group": 0},

    # =================== 6. INCOME (6000-6999) ===================
    {"account_number": "6000", "account_name_en": "Income Account",
     "account_name_hy": "Եկամուտներ",
     "root_type": "Income", "account_type": None, "parent_account_number": None,
     "is_group": 1},
    {"account_number": "6100", "account_name_en": "Sales Revenue",
     "account_name_hy": "Վաճառքի եկամուտ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6000", "is_group": 1},
    {"account_number": "6110", "account_name_en": "Sales of Goods",
     "account_name_hy": "Ապրանքների վաճառք",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6100", "is_group": 1},
    {"account_number": "6111", "account_name_en": "Sales of Goods - Domestic",
     "account_name_hy": "Ապրանքների վաճառք՝ ներքին",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6110", "is_group": 0},
    {"account_number": "6112", "account_name_en": "Sales of Goods - Export",
     "account_name_hy": "Ապրանքների վաճառք՝ արտահանում",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6110", "is_group": 0},
    {"account_number": "6113", "account_name_en": "Sales of Goods - EAEU",
     "account_name_hy": "Ապրանքների վաճառք՝ ԵԱՏՄ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6110", "is_group": 0},
    {"account_number": "6120", "account_name_en": "Sales of Services",
     "account_name_hy": "Ծառայությունների վաճառք",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6100", "is_group": 1},
    {"account_number": "6121", "account_name_en": "Consulting Services",
     "account_name_hy": "Խորհրդատվական ծառայություններ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6120", "is_group": 0},
    {"account_number": "6122", "account_name_en": "Transportation Services",
     "account_name_hy": "Տրանսպորտային ծառայություններ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6120", "is_group": 0},
    {"account_number": "6123", "account_name_en": "Maintenance Services",
     "account_name_hy": "Սպասարկման ծառայություններ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6120", "is_group": 0},
    {"account_number": "6130", "account_name_en": "Sales Returns and Allowances",
     "account_name_hy": "Վաճառքի վերադարձ և զեղչեր",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6100", "is_group": 0},
    {"account_number": "6140", "account_name_en": "Sales Discounts",
     "account_name_hy": "Վաճառքի զեղչեր",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6100", "is_group": 0},
    {"account_number": "6200", "account_name_en": "Other Operating Income",
     "account_name_hy": "Այլ գործառնական եկամուտներ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6000", "is_group": 1},
    {"account_number": "6210", "account_name_en": "Rental Income",
     "account_name_hy": "Վարձակալության եկամուտ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6200", "is_group": 0},
    {"account_number": "6220", "account_name_en": "Royalties",
     "account_name_hy": "Ռոյալթիներ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6200", "is_group": 0},
    {"account_number": "6230", "account_name_en": "Commissions Received",
     "account_name_hy": "Ստացված միջնորդավճարներ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6200", "is_group": 0},
    {"account_number": "6240", "account_name_en": "Gain on Disposal of Assets",
     "account_name_hy": "Ակտիվների օտարման շահույթ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6200", "is_group": 0},
    {"account_number": "6300", "account_name_en": "Financial Income",
     "account_name_hy": "Ֆինանսական եկամուտներ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6000", "is_group": 1},
    {"account_number": "6310", "account_name_en": "Interest Income",
     "account_name_hy": "Տոկոսային եկամուտ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6300", "is_group": 0},
    {"account_number": "6311", "account_name_en": "Interest on Bank Deposits",
     "account_name_hy": "Բանկային ավանդների տոկոս",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6310", "is_group": 0},
    {"account_number": "6312", "account_name_en": "Interest on Loans Granted",
     "account_name_hy": "Տրամադրված վարկերի տոկոս",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6310", "is_group": 0},
    {"account_number": "6320", "account_name_en": "Dividend Income",
     "account_name_hy": "Դիվիդենդային եկամուտ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6300", "is_group": 0},
    {"account_number": "6330", "account_name_en": "Foreign Exchange Gain",
     "account_name_hy": "Արտարժութային փոխանակման շահույթ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6300", "is_group": 0},
    {"account_number": "6400", "account_name_en": "Non-operating Income",
     "account_name_hy": "Ոչ գործառնական եկամուտներ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6000", "is_group": 1},
    {"account_number": "6410", "account_name_en": "Government Grants",
     "account_name_hy": "Պետական դոտացիաներ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6400", "is_group": 0},
    {"account_number": "6420", "account_name_en": "Penalties and Fines Received",
     "account_name_hy": "Ստացված տուգանքներ և տույժեր",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6400", "is_group": 0},
    {"account_number": "6430", "account_name_en": "Donations Received",
     "account_name_hy": "Ստացված նվիրատվություններ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6400", "is_group": 0},
    {"account_number": "6440", "account_name_en": "Insurance Compensation",
     "account_name_hy": "Ապահովագրական հատուցում",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6400", "is_group": 0},
    {"account_number": "6500", "account_name_en": "Reversal of Provisions",
     "account_name_hy": "Վերականգնված պահուստներ",
     "root_type": "Income", "account_type": "Income Account",
     "parent_account_number": "6000", "is_group": 0},

    # =================== 7. EXPENSES (7000-7999) ===================
    {"account_number": "7000", "account_name_en": "Expenses",
     "account_name_hy": "Ծախսեր",
     "root_type": "Expense", "account_type": None, "parent_account_number": None,
     "is_group": 1},
    {"account_number": "7100", "account_name_en": "Cost of Sales",
     "account_name_hy": "Վաճառված ապրանքների ինքնարժեք",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "7000", "is_group": 1},
    {"account_number": "7110", "account_name_en": "Cost of Goods Sold",
     "account_name_hy": "Վաճառված ապրանքների ինքնարժեք",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "7100", "is_group": 0},
    {"account_number": "7111", "account_name_en": "COGS - Domestic Sales",
     "account_name_hy": "Ինքնարժեք՝ ներքին վաճառքի",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "7110", "is_group": 0},
    {"account_number": "7112", "account_name_en": "COGS - Export",
     "account_name_hy": "Ինքնարժեք՝ արտահանման",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "7110", "is_group": 0},
    {"account_number": "7120", "account_name_en": "Direct Labor",
     "account_name_hy": "Ուղղակի աշխատուժ",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "7100", "is_group": 0},
    {"account_number": "7130", "account_name_en": "Manufacturing Overhead",
     "account_name_hy": "Արտադրական ընդհանուր ծախսեր",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "7100", "is_group": 0},
    {"account_number": "7200", "account_name_en": "Operating Expenses",
     "account_name_hy": "Գործառնական ծախսեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7000", "is_group": 1},
    {"account_number": "7210", "account_name_en": "Selling Expenses",
     "account_name_hy": "Վաճառքի ծախսեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7200", "is_group": 1},
    {"account_number": "7211", "account_name_en": "Advertising and Marketing",
     "account_name_hy": "Գովազդ և մարկետինգ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7210", "is_group": 0},
    {"account_number": "7212", "account_name_en": "Trade Shows and Exhibitions",
     "account_name_hy": "Ցուցահանդեսներ և միջոցառումներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7210", "is_group": 0},
    {"account_number": "7213", "account_name_en": "Sales Commissions",
     "account_name_hy": "Վաճառքի միջնորդավճարներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7210", "is_group": 0},
    {"account_number": "7214", "account_name_en": "Delivery and Shipping",
     "account_name_hy": "Առաքում և տրանսպորտ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7210", "is_group": 0},
    {"account_number": "7220", "account_name_en": "Administrative Expenses",
     "account_name_hy": "Վարչական ծախսեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7200", "is_group": 1},
    {"account_number": "7221", "account_name_en": "Office Supplies",
     "account_name_hy": "Գրասենյակային պարագաներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7220", "is_group": 0},
    {"account_number": "7222", "account_name_en": "Postage and Courier",
     "account_name_hy": "Փոստ և սուրհանդակային",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7220", "is_group": 0},
    {"account_number": "7223", "account_name_en": "Printing and Stationery",
     "account_name_hy": "Տպագրություն և գրասենյակային պիտույքներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7220", "is_group": 0},
    {"account_number": "7224", "account_name_en": "Bank Charges",
     "account_name_hy": "Բանկային ծառայությունների վճարներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7220", "is_group": 0},
    {"account_number": "7225", "account_name_en": "Audit and Consulting Fees",
     "account_name_hy": "Աուդիտի և խորհրդատվության վճարներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7220", "is_group": 0},
    {"account_number": "7226", "account_name_en": "Legal Fees",
     "account_name_hy": "Իրավաբանական վճարներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7220", "is_group": 0},
    {"account_number": "7230", "account_name_en": "Rent Expense",
     "account_name_hy": "Վարձավճար",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7200", "is_group": 1},
    {"account_number": "7231", "account_name_en": "Office Rent",
     "account_name_hy": "Գրասենյակի վարձավճար",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7230", "is_group": 0},
    {"account_number": "7232", "account_name_en": "Warehouse Rent",
     "account_name_hy": "Պահեստի վարձավճար",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7230", "is_group": 0},
    {"account_number": "7233", "account_name_en": "Equipment Rent",
     "account_name_hy": "Սարքավորանքի վարձավճար",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7230", "is_group": 0},
    {"account_number": "7240", "account_name_en": "Utilities",
     "account_name_hy": "Կոմունալ վճարներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7200", "is_group": 1},
    {"account_number": "7241", "account_name_en": "Electricity",
     "account_name_hy": "Էլեկտրաէներգիա",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7240", "is_group": 0},
    {"account_number": "7242", "account_name_en": "Gas",
     "account_name_hy": "Գազ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7240", "is_group": 0},
    {"account_number": "7243", "account_name_en": "Water and Sewage",
     "account_name_hy": "Ջուր և կոյուղի",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7240", "is_group": 0},
    {"account_number": "7244", "account_name_en": "Heating",
     "account_name_hy": "Ջեռուցում",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7240", "is_group": 0},
    {"account_number": "7245", "account_name_en": "Telecommunications",
     "account_name_hy": "Հեռահաղորդակցություն",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7240", "is_group": 0},
    {"account_number": "7246", "account_name_en": "Internet Services",
     "account_name_hy": "Ինտերնետ ծառայություններ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7240", "is_group": 0},
    {"account_number": "7250", "account_name_en": "Depreciation and Amortization",
     "account_name_hy": "Մաշվածք և արժեկում",
     "root_type": "Expense", "account_type": "Depreciation",
     "parent_account_number": "7200", "is_group": 1},
    {"account_number": "7251", "account_name_en": "Depreciation - Buildings",
     "account_name_hy": "Մաշվածք՝ շենքեր",
     "root_type": "Expense", "account_type": "Depreciation",
     "parent_account_number": "7250", "is_group": 0},
    {"account_number": "7252", "account_name_en": "Depreciation - Machinery",
     "account_name_hy": "Մաշվածք՝ մեքենաներ",
     "root_type": "Expense", "account_type": "Depreciation",
     "parent_account_number": "7250", "is_group": 0},
    {"account_number": "7253", "account_name_en": "Depreciation - Vehicles",
     "account_name_hy": "Մաշվածք՝ տրանսպորտային միջոցներ",
     "root_type": "Expense", "account_type": "Depreciation",
     "parent_account_number": "7250", "is_group": 0},
    {"account_number": "7254", "account_name_en": "Amortization - Intangibles",
     "account_name_hy": "Արժեկում՝ աննյութական ակտիվներ",
     "root_type": "Expense", "account_type": "Depreciation",
     "parent_account_number": "7250", "is_group": 0},
    {"account_number": "7260", "account_name_en": "Repairs and Maintenance",
     "account_name_hy": "Վերանորոգում և սպասարկում",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7200", "is_group": 0},
    {"account_number": "7261", "account_name_en": "Maintenance - Buildings",
     "account_name_hy": "Սպասարկում՝ շենքեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7260", "is_group": 0},
    {"account_number": "7262", "account_name_en": "Maintenance - Equipment",
     "account_name_hy": "Սպասարկում՝ սարքավորանքներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7260", "is_group": 0},
    {"account_number": "7263", "account_name_en": "Maintenance - Vehicles",
     "account_name_hy": "Սպասարկում՝ մեքենաներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7260", "is_group": 0},
    {"account_number": "7270", "account_name_en": "Insurance Expense",
     "account_name_hy": "Ապահովագրական ծախսեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7200", "is_group": 1},
    {"account_number": "7271", "account_name_en": "Property Insurance",
     "account_name_hy": "Գույքի ապահովագրություն",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7270", "is_group": 0},
    {"account_number": "7272", "account_name_en": "Vehicle Insurance",
     "account_name_hy": "Տրանսպորտային միջոցների ապահովագրություն",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7270", "is_group": 0},
    {"account_number": "7273", "account_name_en": "Liability Insurance",
     "account_name_hy": "Պարտավորությունների ապահովագրություն",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7270", "is_group": 0},
    {"account_number": "7280", "account_name_en": "Travel and Entertainment",
     "account_name_hy": "Ուղևորություններ և ներկայացուցչական ծախսեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7200", "is_group": 1},
    {"account_number": "7281", "account_name_en": "Travel Expenses",
     "account_name_hy": "Ուղևորության ծախսեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7280", "is_group": 0},
    {"account_number": "7282", "account_name_en": "Hotel and Accommodation",
     "account_name_hy": "Հյուրանոց և բնակություն",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7280", "is_group": 0},
    {"account_number": "7283", "account_name_en": "Meals and Entertainment",
     "account_name_hy": "Սնունդ և ներկայացուցչական",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7280", "is_group": 0},
    {"account_number": "7290", "account_name_en": "Training and Education",
     "account_name_hy": "Վերապատրաստում և կրթություն",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7200", "is_group": 0},
    {"account_number": "7300", "account_name_en": "Personnel Costs",
     "account_name_hy": "Անձնակազմի ծախսեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7000", "is_group": 1},
    {"account_number": "7310", "account_name_en": "Salaries and Wages",
     "account_name_hy": "Աշխատավարձեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7300", "is_group": 0},
    {"account_number": "7311", "account_name_en": "Base Salary",
     "account_name_hy": "Հիմնական աշխատավարձ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7310", "is_group": 0},
    {"account_number": "7312", "account_name_en": "Overtime Pay",
     "account_name_hy": "Հերթափոխային վճար",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7310", "is_group": 0},
    {"account_number": "7313", "account_name_en": "Bonuses",
     "account_name_hy": "Պարգևավճարներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7310", "is_group": 0},
    {"account_number": "7320", "account_name_en": "Social Contributions",
     "account_name_hy": "Սոցիալական վճարներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7300", "is_group": 0},
    {"account_number": "7321", "account_name_en": "Pension Contributions",
     "account_name_hy": "Կենսաթոշակային վճարներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7320", "is_group": 0},
    {"account_number": "7322", "account_name_en": "Medical Insurance Contributions",
     "account_name_hy": "Բժշկական ապահովագրության վճարներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7320", "is_group": 0},
    {"account_number": "7330", "account_name_en": "Employee Benefits",
     "account_name_hy": "Աշխատակիցների արտոնություններ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7300", "is_group": 0},
    {"account_number": "7400", "account_name_en": "Tax Expenses",
     "account_name_hy": "Հարկային ծախսեր",
     "root_type": "Expense", "account_type": "Tax",
     "parent_account_number": "7000", "is_group": 1},
    {"account_number": "7410", "account_name_en": "Profit Tax Expense",
     "account_name_hy": "Շահութահարկի ծախս",
     "root_type": "Expense", "account_type": "Tax",
     "parent_account_number": "7400", "is_group": 0},
    {"account_number": "7420", "account_name_en": "Property Tax Expense",
     "account_name_hy": "Գույքահարկի ծախս",
     "root_type": "Expense", "account_type": "Tax",
     "parent_account_number": "7400", "is_group": 0},
    {"account_number": "7430", "account_name_en": "Land Tax Expense",
     "account_name_hy": "Հողահարկի ծախս",
     "root_type": "Expense", "account_type": "Tax",
     "parent_account_number": "7400", "is_group": 0},
    {"account_number": "7440", "account_name_en": "Non-deductible VAT",
     "account_name_hy": "Հսկողության դուրս ԱԱՀ",
     "root_type": "Expense", "account_type": "Tax",
     "parent_account_number": "7400", "is_group": 0},
    {"account_number": "7450", "account_name_en": "Environmental Charges",
     "account_name_hy": "Բնապահպանական վճարներ",
     "root_type": "Expense", "account_type": "Tax",
     "parent_account_number": "7400", "is_group": 0},
    {"account_number": "7460", "account_name_en": "State Duties and Fees",
     "account_name_hy": "Պետական տուրքեր և վճարներ",
     "root_type": "Expense", "account_type": "Tax",
     "parent_account_number": "7400", "is_group": 0},
    {"account_number": "7500", "account_name_en": "Financial Expenses",
     "account_name_hy": "Ֆինանսական ծախսեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7000", "is_group": 1},
    {"account_number": "7510", "account_name_en": "Interest Expense",
     "account_name_hy": "Տոկոսային ծախսեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7500", "is_group": 0},
    {"account_number": "7511", "account_name_en": "Interest on Bank Loans",
     "account_name_hy": "Բանկային վարկերի տոկոս",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7510", "is_group": 0},
    {"account_number": "7512", "account_name_en": "Interest on Bonds",
     "account_name_hy": "Պարտատոմսերի տոկոս",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7510", "is_group": 0},
    {"account_number": "7520", "account_name_en": "Foreign Exchange Loss",
     "account_name_hy": "Արտարժութային փոխանակման վնաս",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7500", "is_group": 0},
    {"account_number": "7530", "account_name_en": "Loss on Disposal of Assets",
     "account_name_hy": "Ակտիվների օտարման վնաս",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7500", "is_group": 0},
    {"account_number": "7600", "account_name_en": "Bad Debts Expense",
     "account_name_hy": "Կասկածելի պարտքերի ծախսեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7000", "is_group": 0},
    {"account_number": "7610", "account_name_en": "Write-offs of Receivables",
     "account_name_hy": "Պարտքերի մուծում",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7600", "is_group": 0},
    {"account_number": "7620", "account_name_en": "Provisions for Receivables",
     "account_name_hy": "Պարտքերի համար պահուստներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7600", "is_group": 0},
    {"account_number": "7700", "account_name_en": "Penalties and Fines",
     "account_name_hy": "Տուգանքներ և տույժեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7000", "is_group": 0},
    {"account_number": "7800", "account_name_en": "Charitable Contributions",
     "account_name_hy": "Բարեգործական ներդրումներ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7000", "is_group": 0},
    {"account_number": "7900", "account_name_en": "Other Operating Expenses",
     "account_name_hy": "Այլ գործառնական ծախսեր",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7000", "is_group": 1},
    {"account_number": "7910", "account_name_en": "Office Cleaning",
     "account_name_hy": "Գրասենյակի մաքրում",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7900", "is_group": 0},
    {"account_number": "7920", "account_name_en": "Security Services",
     "account_name_hy": "Անվտանգության ծառայություններ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7900", "is_group": 0},
    {"account_number": "7930", "account_name_en": "Subscriptions and Memberships",
     "account_name_hy": "Բաժանորդագրություններ և անդամակցություններ",
     "root_type": "Expense", "account_type": "Expense Account",
     "parent_account_number": "7900", "is_group": 0},

    # =================== 8. OFF-BALANCE-SHEET (8000-8999) ===================
    {"account_number": "8000", "account_name_en": "Off-balance-sheet Accounts",
     "account_name_hy": "Հաշվից դուրս հաշիվներ",
     "root_type": "Liability", "account_type": None, "parent_account_number": None,
     "is_group": 1},
    {"account_number": "8100", "account_name_en": "Assets Held in Trust",
     "account_name_hy": "Հանձնարարությամբ պահվող ակտիվներ",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8000", "is_group": 1},
    {"account_number": "8110", "account_name_en": "Goods Received on Consignment",
     "account_name_hy": "Կոնսիգնացիոն կարգով ստացված ապրանքներ",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8100", "is_group": 0},
    {"account_number": "8120", "account_name_en": "Materials for Processing",
     "account_name_hy": "Վերամշակման համար նյութեր",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8100", "is_group": 0},
    {"account_number": "8200", "account_name_en": "Commitments and Guarantees",
     "account_name_hy": "Պարտավորություններ և երաշխիքներ",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8000", "is_group": 1},
    {"account_number": "8210", "account_name_en": "Guarantees Given",
     "account_name_hy": "Տրված երաշխիքներ",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8200", "is_group": 0},
    {"account_number": "8220", "account_name_en": "Guarantees Received",
     "account_name_hy": "Ստացված երաշխիքներ",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8200", "is_group": 0},
    {"account_number": "8230", "account_name_en": "Letters of Credit",
     "account_name_hy": "Ակրեդիտիվներ",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8200", "is_group": 0},
    {"account_number": "8240", "account_name_en": "Pledged Assets",
     "account_name_hy": "Գրավով բեռնված ակտիվներ",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8200", "is_group": 0},
    {"account_number": "8300", "account_name_en": "Leased Assets",
     "account_name_hy": "Վարձակալված ակտիվներ",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8000", "is_group": 1},
    {"account_number": "8310", "account_name_en": "Operating Leases - Asset Value",
     "account_name_hy": "Գործառնական վարձակալություն՝ ակտիվի արժեք",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8300", "is_group": 0},
    {"account_number": "8320", "account_name_en": "Operating Leases - Future Payments",
     "account_name_hy": "Գործառնական վարձակալություն՝ ապագա վճարներ",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8300", "is_group": 0},
    {"account_number": "8400", "account_name_en": "Bad Debts Written Off",
     "account_name_hy": "Մուծված վատ պարտքեր",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8000", "is_group": 0},
    {"account_number": "8500", "account_name_en": "Securities Held for Safekeeping",
     "account_name_hy": "Պահպանման համար ընդունված արժեթղթեր",
     "root_type": "Liability", "account_type": "",
     "parent_account_number": "8000", "is_group": 0},

    # =================== 9. COST OF GOODS SOLD (9000-9999) ===================
    {"account_number": "9000", "account_name_en": "Cost of Goods Sold (Detailed)",
     "account_name_hy": "Ապրանքների ինքնարժեք (մանրամասն)",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": None, "is_group": 1},
    {"account_number": "9100", "account_name_en": "Material Costs",
     "account_name_hy": "Նյութական ծախսեր",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9000", "is_group": 1},
    {"account_number": "9110", "account_name_en": "Raw Materials Used",
     "account_name_hy": "Օգտագործված հումք",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9100", "is_group": 0},
    {"account_number": "9120", "account_name_en": "Packaging Materials Used",
     "account_name_hy": "Օգտագործված փաթեթավորման նյութեր",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9100", "is_group": 0},
    {"account_number": "9130", "account_name_en": "Fuel and Energy for Production",
     "account_name_hy": "Արտադրության վառելիք և էներգիա",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9100", "is_group": 0},
    {"account_number": "9200", "account_name_en": "Direct Labor Costs",
     "account_name_hy": "Ուղղակի աշխատուժի ծախսեր",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9000", "is_group": 1},
    {"account_number": "9210", "account_name_en": "Production Workers' Wages",
     "account_name_hy": "Արտադրական աշխատողների աշխատավարձեր",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9200", "is_group": 0},
    {"account_number": "9220", "account_name_en": "Production Workers' Social Contributions",
     "account_name_hy": "Արտադրական աշխատողների սոցիալական վճարներ",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9200", "is_group": 0},
    {"account_number": "9300", "account_name_en": "Production Overhead",
     "account_name_hy": "Արտադրական ընդհանուր ծախսեր",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9000", "is_group": 1},
    {"account_number": "9310", "account_name_en": "Equipment Depreciation - Production",
     "account_name_hy": "Սարքավորանքի մաշվածք՝ արտադրություն",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9300", "is_group": 0},
    {"account_number": "9320", "account_name_en": "Production Rent",
     "account_name_hy": "Արտադրական վարձավճար",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9300", "is_group": 0},
    {"account_number": "9330", "account_name_en": "Production Insurance",
     "account_name_hy": "Արտադրական ապահովագրություն",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9300", "is_group": 0},
    {"account_number": "9340", "account_name_en": "Repair of Production Equipment",
     "account_name_hy": "Արտադրական սարքավորանքի վերանորոգում",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9300", "is_group": 0},
    {"account_number": "9400", "account_name_en": "Subcontracting Costs",
     "account_name_hy": "Ենթապայմանագրային ծախսեր",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9000", "is_group": 0},
    {"account_number": "9500", "account_name_en": "Freight and Customs",
     "account_name_hy": "Տրանսպորտ և մաքսային ծախսեր",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9000", "is_group": 1},
    {"account_number": "9510", "account_name_en": "Inbound Freight",
     "account_name_hy": "Մուտքային տրանսպորտ",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9500", "is_group": 0},
    {"account_number": "9520", "account_name_en": "Customs Duties",
     "account_name_hy": "Մաքսային տուրքեր",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9500", "is_group": 0},
    {"account_number": "9530", "account_name_en": "Insurance in Transit",
     "account_name_hy": "Տրանսպորտի ապահովագրություն",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9500", "is_group": 0},
    {"account_number": "9600", "account_name_en": "Inventory Adjustments",
     "account_name_hy": "Պաշարների ճշգրտումներ",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9000", "is_group": 0},
    {"account_number": "9700", "account_name_en": "Warranty Costs",
     "account_name_hy": "Երաշխիքային ծախսեր",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9000", "is_group": 0},
    {"account_number": "9800", "account_name_en": "Other Production Costs",
     "account_name_hy": "Այլ արտադրական ծախսեր",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9000", "is_group": 0},
    {"account_number": "9900", "account_name_en": "Cost Variances",
     "account_name_hy": "Ծախսերի շեղումներ",
     "root_type": "Expense", "account_type": "Cost of Goods Sold",
     "parent_account_number": "9000", "is_group": 0},
]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_coa_tree() -> list[dict]:
    """Return the full Armenian COA as a list of plain dicts.

    Each dict has:
        account_number          str, e.g. "1000"
        account_name_en         str
        account_name_hy         str (Armenian)
        root_type               str (Asset/Liability/Equity/Income/Expense)
        account_type            str or None
        parent_account_number   str or None
        is_group                int (0/1)  -- auto-set: 1 for any account that
                                                 has children in this tree.
    """
    raw = [dict(entry) for entry in COA_ENTRIES]
    # Auto-mark accounts that have children as groups, so ERPNext's
    # 'parent cannot be a ledger' validator passes on insert.
    parent_numbers = {e["parent_account_number"] for e in raw if e.get("parent_account_number")}
    for e in raw:
        if e["account_number"] in parent_numbers:
            e["is_group"] = 1
    # ERPNext's validate_parent_child_account_type rejects a child whose
    # type matches one of {Current Asset, Current Liability, Direct Income/Expense,
    # Indirect Income/Expense}. Strip the type from any non-group account.
    for e in raw:
        if not e["is_group"] and e["account_type"] in (
            "Current Asset", "Current Liability",
            "Direct Income", "Direct Expense",
            "Indirect Income", "Indirect Expense",
        ):
            e["account_type"] = None
    return raw


def count_by_root_type(tree: list[dict]) -> dict[str, int]:
    """Return a tally of accounts by root_type."""
    return dict(Counter(a["root_type"] for a in tree))


def seed_armenian_coa(company: str) -> int:
    """Insert all Armenian-standard accounts under the given company.

    Idempotent: an account that already exists for the company
    (same account_number) is silently skipped, not duplicated.
    Returns the number of accounts that were newly created.

    Requires an active Frappe site context (e.g. via `bench execute`
    or inside a Frappe request/job).
    """
    import frappe

    if not frappe.db.exists("Company", company):
        raise ValueError(f"Company {company!r} does not exist")

    tree = build_coa_tree()
    by_num: dict[str, str] = {}
    created = 0
    for entry in tree:
        num = entry["account_number"]
        if frappe.db.exists(
            "Account", {"account_number": num, "company": company}
        ):
            # Already seeded: record the existing name so children can link
            existing_name = frappe.db.get_value(
                "Account",
                {"account_number": num, "company": company},
                "name",
            )
            by_num[num] = existing_name
            continue

        doc = frappe.new_doc("Account")
        doc.company = company
        doc.account_number = num
        doc.account_name = entry["account_name_en"]
        doc.root_type = entry["root_type"]
        doc.account_type = entry["account_type"] or ""
        doc.is_group = int(entry.get("is_group", 0))
        parent_num = entry.get("parent_account_number")
        if parent_num and parent_num in by_num:
            doc.parent_account = by_num[parent_num]
        doc.insert(ignore_permissions=True, ignore_mandatory=True)
        by_num[num] = doc.name
        created += 1
    return created
